# Generated by Django 4.2.15 on 2024-09-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.CharField(help_text='Enter an id starting with PERM and 3 digit number eg:PERM101', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(help_text='Start with ROL and add a number. eg: ROL101', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
