# Generated by Django 4.2.15 on 2024-09-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_permissions_alter_role_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterField(
            model_name='permissions',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterModelTable(
            name='permissions',
            table='permissions',
        ),
    ]
